package:
  name: opencv3
  version: 3.2.0

source:
  git_url: https://github.com/opencv/opencv.git
  git_rev: 3.2.0

requirements:
  build:
   - python >=3.5
   - cmake
   - hdf5 1.8.*      # [osx]
   - numpy >=1.10
   - eigen 3.*
   - tbb 4.3*        # [osx]
   - msinttypes r26  # [win and py<35]

  run:
   - python >=3.5
   - numpy >=1.10
   - hdf5 1.8.*  # [osx]
   - tbb 4.3*    # [osx]

# test:
#   imports:
#     - cv2
#     - cv2.xfeatures2d

about:
  home: http://opencv.org/
  license: BSD
